services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: erp
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root123

  backend-api:
    build:
      context: ./backend-api
    container_name: backend-api
    restart: always
    ports:
      - "5120:5120"
    environment:
      DATABASE_URL: mysql://root:root123@mysql:3306/erp
      FRONTEND_URL: http://localhost:3000
      JWT_SECRET: 8cc0dd22fdec33af13ea9e9809f68a90
      PORT: 5120
    depends_on:
      - mysql
    volumes:
      - ./backend-api:/app
    working_dir: /app
    command: npm run dev

  host-app:
    build:
      context: ./host-app
    container_name: host-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: /api
      PORT: 3000
    depends_on:
      - backend-api
    volumes:
      - ./host-app:/app
    working_dir: /app
    command: npm run serve

  remote-app:
    build:
      context: ./remote-app
    container_name: remote-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      REACT_APP_API_URL: /api
      PORT: 3001
    depends_on:
      - backend-api
    volumes:
      - ./remote-app:/app
    working_dir: /app
    command: npm run serve
  remote-app-product:
    build:
      context: ./remote-app-product
    container_name: remote-app-product
    restart: always
    ports:
      - "3002:3002"
    environment:
      REACT_APP_API_URL: /api
      PORT: 3002
    depends_on:
      - backend-api
    volumes:
      - ./remote-app-product:/app
    working_dir: /app
    command: npm run serve

volumes:
  mysql_data:
